site_name: RP-Helpdesk Docs
site_url: https://rp-helpdesk.com/
repo_name: Rune004/mkdocs
repo_url: https://github.com/rune004/mkdocs/
nav:
    - Introduction: 
        - 'Welcome To RPH': 'index.md'
        - 'About RPH': 'about.md'
        - 'Our Blog Posts': 
          - 'Coming Soon': '.'
    - Documentation:
      - Ansible Documentation:
        - 'What is Ansible?': 'ansible.md'
        - Automated Test Environment: 
          - 'Setup/Install Ansible': 'ansible-setup.md'
          - 'Configure a Ansible playbook': 'ansible-playbook.md'
          - 'Use a Ansible-playbook': 'ansible-use.md'
      - Proxmox Documentation:
        - 'What is Proxmox?': 'proxmox.md'
        - 'Proxmox Errors': 'proxmox-errors.md'
      - Docker Documentation:
        - 'What is Docker?': 'docker.md'
        - Portainer:
          - 'What is Portainer?': 'portainer.md'
          - 'Custom Docker-Compose': 'docker-customcompose.md'
theme:
  icon:
      repo: fontawesome/brands/gitkraken
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: black
      accent: red

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: black
      accent: red

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: black
      accent: red
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
markdown_extensions:
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - attr_list:
    - toc:
        permalink: "#"
        separator: "_"
copyright: Copyright &copy; 2022 RP-Helpdesk 
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rune004

    - icon: fontawesome/brands/linkedin
      link: https://twitter.com/squidfunk
    
    - icon: fontawesome/brands/slack
      link: https://twitter.com/squidfunk
  