site_name: RP-Helpdesk Docs
site_url: https://rp-helpdesk.com/
repo_name: Rune004/mkdocs
repo_url: https://github.com/rune004/mkdocs/
use_directory_urls: false
nav:
    - Introduction:
      - Introduction To RPH:
        - Welcome To RPH: 'index.md'
        - About RPH: 'about.md'
      - What is?: 
        - What is Ansible?: 'ansible.md'
        - What is Proxmox?: 'proxmox.md'
        - What is Docker?: 'docker.md'
        - What is Portainer?: 'portainer.md'
      - Our Software:
        - 'Windows Auto Installer': 'windows-auto-installer.md' 
    - Documentation:
      - Ansible Documentation:
        - 'What is Ansible?': 'ansible.md'
        - Automated Test Environment: 
          - 'Setup/Install Ansible': 'ansible-setup.md'
          - 'Configure a Ansible playbook': 'ansible-playbook.md'
          - 'Use a Ansible-playbook': 'ansible-use.md'
      - Proxmox Documentation:
        - 'What is Proxmox?': 'proxmox.md'
        - 'Proxmox Errors': 'proxmox-errors.md'
      - Docker Documentation:
        - 'What is Docker?': 'docker.md'
        - 'Setup Docker': 'portainer-setup.html#install-docker-ce'
        - Portainer:
          - 'What is Portainer?': 'portainer.md'
          - 'Setup Portainer': 'portainer-setup.md'
          - 'Custom Docker-Compose': 'docker-customcompose.md'
      - Unraid Documentation:
        - 'What is Unraid': 'unraid.md'
        - Unraid Getting Started:
          - 'Cloudflare Tunnel': 'unraid-cloudflared.md'  
    - Blog:
      - Servers: 
        - 'Power Efficient Home Server': 'power-efficient-home-server.md'
    - Software:
      - Our Software:
        - 'Windows Auto Installer': 'windows-auto-installer.md'
      - Software we recommend: 
        - 'Self-Hosted Vaultwarden': 'docker-customcompose.html#vaultwarden'
        - 'Self-Hosted Seafile': 'docker-customcompose.html#seafile'
        - 'Self-Hosted Vikunja': 'docker-customcompose.html#vikunja'
        - 'Self-Hosted Flamedashboard': 'docker-customcompose.html#flamedashboard' 
theme:
  icon:
      repo: fontawesome/brands/gitkraken
      admonition:
        note: material/notebook-edit
        abstract: material/file-edit
        info: material/notebook-check
        tip: material/tooltip-check-outline
        success: simple/riseup
        question: octicons/question-16
        warning: fontawesome/solid/person-military-pointing
        failure: octicons/x-circle-16
        danger: octicons/zap-16
        bug: material/docker
        example: material/monitor-edit
        quote: octicons/quote-16
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: black
      accent: indigo

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: black
      accent: indigo

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: black
      accent: indigo
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
plugins:
  - search
  - git-authors
  - git-revision-date-localized
  - git-committers:
      repository: rune004/mkdocs
      branch: master
  - minify:
      minify_html: true
copyright: Copyright &copy; 2022 RP-Helpdesk 
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rune004

    - icon: fontawesome/brands/linkedin
      link: https://twitter.com/squidfunk


