site_name: RP-Helpdesk Docs
site_url: https://rp-helpdesk.com/
repo_name: Rune004/mkdocs
repo_url: https://github.com/rune004/mkdocs/
use_directory_urls: false
nav:
    - Introduction: 
        - Welcome To RPH: 'index.md'
        - About RPH: 'about.md'
    - Documentation:
      - Ansible Documentation:
        - 'What is Ansible?': 'ansible.md'
        - Automated Test Environment: 
          - 'Setup/Install Ansible': 'ansible-setup.md'
          - 'Configure a Ansible playbook': 'ansible-playbook.md'
          - 'Use a Ansible-playbook': 'ansible-use.md'
      - Proxmox Documentation:
        - 'What is Proxmox?': 'proxmox.md'
        - 'Proxmox Errors': 'proxmox-errors.md'
      - Docker Documentation:
        - 'What is Docker?': 'docker.md'
        - Portainer:
          - 'What is Portainer?': 'portainer.md'
          - 'Custom Docker-Compose': 'docker-customcompose.md'
    - Blog:
      - Servers: 
        - 'Power Efficient Home Server': 'power-efficient-home-server.md'
theme:
  icon:
      repo: fontawesome/brands/gitkraken
      admonition:
        note: octicons/tag-16
        abstract: octicons/checklist-16
        info: octicons/info-16
        tip: octicons/squirrel-16
        success: octicons/check-16
        question: octicons/question-16
        warning: octicons/alert-16
        failure: octicons/x-circle-16
        danger: octicons/zap-16
        bug: octicons/bug-16
        example: octicons/beaker-16
        quote: octicons/quote-16
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: black
      accent: red

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: black
      accent: red

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: black
      accent: red
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - md_in_html
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - attr_list:
    - toc:
        permalink: "#"
        separator: "_"
copyright: Copyright &copy; 2022 RP-Helpdesk 
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rune004

    - icon: fontawesome/brands/linkedin
      link: https://twitter.com/squidfunk


